name: audioplayers_example
description: Demonstrates how to use the audioplayers plugin.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+16
  audioplayers:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/audio.mp3
    - assets/audio2.mp3

environment:
  sdk: ">=2.0.0-dev.50.0 <2.0.0"
