name: audioplayers_example
description: Demonstrates how to use the audioplayers plugin.

dependencies:
  flutter:
    sdk: flutter
  audioplayers:
    path: ../
  http: ^0.12.2
  path_provider: ^1.5.1
  path_provider_macos: ^0.0.4+4
  provider: ^3.0.0+1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

  assets:
    - assets/audio.mp3
    - assets/audio2.mp3
    - assets/messenger.mp3

environment:
  sdk: ">=2.2.2 <3.0.0"
