name: audioplayers_web
description: Web implementation of audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 3.1.0
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers_web

flutter:
  plugin:
    platforms:
      web:
        pluginClass: AudioplayersPlugin
        fileName: audioplayers_web.dart

dependencies:
  audioplayers_platform_interface: ^5.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.4

dev_dependencies:
  dartdoc: ^6.1.5
  flame_lint: ^1.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"
