name: audioplayers_platform_interface
description: The platform interface for audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 1.0.0-rc.2
homepage: https://github.com/luanpotter/audioplayers

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_lint:
    git:
      url: 'https://github.com/flame-engine/flame.git'
      path: 'packages/flame_lint'
  dartdoc: ^5.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"
