name: audioplayers_platform_interface
description: The platform interface for audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 5.0.0
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers_platform_interface

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  dartdoc: ^6.1.5
  flame_lint: ^0.2.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"
