name: audioplayers_example
description: Demonstrates how to use the audioplayers plugin.
publish_to: none

dependencies:
  audioplayers: ^4.0.1
  collection: ^1.16.0
  file_picker: ^5.0.1
  flutter:
    sdk: flutter
  http: ^0.13.1
  path_provider: ^2.0.12
  provider: ^6.0.5
  screenshot: ^1.3.0

dev_dependencies:
  # Integration tests for audioplayers_platform_interface are handled 
  # in this package to avoid maintaining multiple example apps:
  audioplayers_platform_interface: ^5.0.0
  flame_lint: ^0.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"
