name: audioplayers_example
description: Demonstrates how to use the audioplayers plugin.

dependencies:
  flutter:
    sdk: flutter
  audioplayers:
    path: ../
  http: ^0.13.1
  path_provider: ^2.0.1
  path_provider_macos: ^2.0.0
  provider: 5.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flame_lint: 0.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"
