name: audioplayers_example
resolution: workspace
description: Demonstrates how to use the audioplayers plugin.
publish_to: none

dependencies:
  audioplayers: ^6.5.1
  collection: ^1.16.0
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  http: ^1.0.0
  integration_test:
    sdk: flutter
  path_provider: ^2.0.12

dev_dependencies:
  # Integration tests for audioplayers_platform_interface are handled 
  # in this package to avoid maintaining multiple example apps:
  audioplayers_platform_interface: ^7.1.1
  flame_lint: ^1.4.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'
