name: audioplayers
description: A Flutter plugin to play multiple audio files simultaneously
version: 0.20.1
homepage: https://github.com/luanpotter/audioplayers
publish_to: none # note: this is just for the linter to pass until we have Melos here

flutter:
  plugin:
    platforms:
      android:
        default_package: audioplayers_android
      ios:
        default_package: audioplayers_darwin
      macos:
        default_package: audioplayers_darwin
      web:
        default_package: audioplayers_web

dependencies:
  audioplayers_platform_interface:
    path: ../audioplayers_platform_interface
  audioplayers_android:
    path: ../audioplayers_android
  audioplayers_darwin:
    path: ../audioplayers_darwin
  audioplayers_web:
    path: ../audioplayers_web
  uuid: ^3.0.1
  path_provider: ^2.0.1
  http: ^0.13.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_lint: 0.0.1
  dartdoc: ^2.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.10.0"

