name: audioplayers
description: A Flutter plugin to play multiple audio files simultaneously
version: 3.0.1
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers

flutter:
  plugin:
    platforms:
      android:
        default_package: audioplayers_android
      ios:
        default_package: audioplayers_darwin
      linux:
        default_package: audioplayers_linux
      macos:
        default_package: audioplayers_darwin
      web:
        default_package: audioplayers_web
      windows:
        default_package: audioplayers_windows

dependencies:
  audioplayers_android: ^2.0.0
  audioplayers_darwin: ^3.0.1
  audioplayers_linux: ^1.0.4
  audioplayers_platform_interface: ^4.0.0
  audioplayers_web: ^2.2.0
  audioplayers_windows: ^1.1.3
  flutter:
    sdk: flutter
  http: ^0.13.5
  meta: ^1.8.0
  path_provider: ^2.0.12
  synchronized: ^3.0.1
  uuid: ^3.0.7

dev_dependencies:
  dartdoc: ^6.1.5
  flame_lint: ^0.2.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

