name: audioplayers
description: A Flutter plugin to play multiple audio files simultaneously
version: 4.1.0
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers

flutter:
  plugin:
    platforms:
      android:
        default_package: audioplayers_android
      ios:
        default_package: audioplayers_darwin
      linux:
        default_package: audioplayers_linux
      macos:
        default_package: audioplayers_darwin
      web:
        default_package: audioplayers_web
      windows:
        default_package: audioplayers_windows

dependencies:
  audioplayers_android: 
   git:
      url: git@github.com:jgrandchavin/audioplayers
      ref:  fix/illegale_state_exception_on_android
      path: packages/audioplayers_android
  audioplayers_darwin: ^4.1.0
  audioplayers_linux: ^2.1.0
  audioplayers_platform_interface: ^5.0.1
  audioplayers_web: ^3.1.0
  audioplayers_windows: ^2.0.2
  file: ^6.1.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  meta: ^1.7.0
  path_provider: ^2.0.12
  synchronized: ^3.0.0
  uuid: ^3.0.7

dev_dependencies:
  dartdoc: ^6.1.5
  flame_lint: ^0.2.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

