name: audioplayers_linux
description: Linux implementation of audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 2.1.0
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers_linux

flutter:
  plugin:
    implements: audioplayers
    platforms:
      linux:
        pluginClass: AudioplayersLinuxPlugin

dependencies:
  audioplayers_platform_interface: ^5.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  dartdoc: ^6.1.5
  flame_lint: ^1.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

