name: audioplayers_linux
description: Linux implementation of audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 1.0.1
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers_linux

flutter:
  plugin:
    implements: audioplayers
    platforms:
      linux:
        pluginClass: AudioplayersLinuxPlugin

dependencies:
  audioplayers_platform_interface: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  dartdoc: ^5.0.1
  flame_lint: ^0.1.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

