name: audioplayers_test_server
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0

dev_dependencies:
  flame_lint: ^0.2.0
  http: ^0.13.0
